// Objective-C API for talking to github.com/0chain/gosdk/mobilesdk/zboxapi Go package.
//   gobind -lang=objc github.com/0chain/gosdk/mobilesdk/zboxapi
//
// File is generated by gobind. Do not edit.

#ifndef __Zboxapi_H__
#define __Zboxapi_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@interface Zboxapi : NSObject
+ (NSError* _Nullable) errZboxApiInvalidWallet;
+ (void) setErrZboxApiInvalidWallet:(NSError* _Nullable)v;

+ (NSError* _Nullable) errZboxApiNotInitialized;
+ (void) setErrZboxApiNotInitialized:(NSError* _Nullable)v;

@end

/**
 * CreateJwtSession create a jwt session
 */
FOUNDATION_EXPORT BOOL ZboxapiCreateJwtSession(NSString* _Nullable phoneNumber, int64_t* _Nullable ret0_, NSError* _Nullable* _Nullable error);

/**
 * CreateJwtToken create a fresh jwt token
 */
FOUNDATION_EXPORT NSString* _Nonnull ZboxapiCreateJwtToken(NSString* _Nullable phoneNumber, int64_t jwtSessionID, NSString* _Nullable otp, NSError* _Nullable* _Nullable error);

/**
 * GetCsrfToken create a fresh CSRF token
 */
FOUNDATION_EXPORT NSString* _Nonnull ZboxapiGetCsrfToken(NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT void ZboxapiInit(NSString* _Nullable baseUrl, NSString* _Nullable appType);

/**
 * RefreshJwtToken refresh jwt token
 */
FOUNDATION_EXPORT NSString* _Nonnull ZboxapiRefreshJwtToken(NSString* _Nullable phoneNumber, NSString* _Nullable token, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT BOOL ZboxapiSetWallet(NSString* _Nullable clientID, NSString* _Nullable clientPrivateKey, NSString* _Nullable clientPublicKey, NSError* _Nullable* _Nullable error);

#endif
