
// Objective-C API for talking to the following Go packages
//
//	github.com/0chain/gosdk/zcncore
//	github.com/0chain/gosdk/core/common
//	github.com/0chain/gosdk/mobilesdk/sdk
//	github.com/0chain/gosdk/mobilesdk/zbox
//	github.com/0chain/gosdk/mobilesdk/zboxapi
//	github.com/0chain/gosdk/mobilesdk/zcn
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Zcncore_FRAMEWORK_H__
#define __Zcncore_FRAMEWORK_H__

#include "Zcncore.objc.h"
#include "Common.objc.h"
#include "Sdk.objc.h"
#include "Zbox.objc.h"
#include "Zboxapi.objc.h"
#include "Zcn.objc.h"
#include "Universe.objc.h"

#endif
