// Objective-C API for talking to github.com/0chain/gosdk/mobilesdk/zcn Go package.
//   gobind -lang=objc github.com/0chain/gosdk/mobilesdk/zcn
//
// File is generated by gobind. Do not edit.

#ifndef __Zcn_H__
#define __Zcn_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"

#include "Zcncore.objc.h"

FOUNDATION_EXPORT NSString* _Nonnull ZcnExecuteSmartContract(NSString* _Nullable address, NSString* _Nullable methodName, NSString* _Nullable input, NSString* _Nullable sasToken, NSError* _Nullable* _Nullable error);

/**
 * Faucet
 */
FOUNDATION_EXPORT NSString* _Nonnull ZcnFaucet(NSString* _Nullable methodName, NSString* _Nullable jsonInput, double zcnToken, NSError* _Nullable* _Nullable error);

/**
 * GetUserLockedTotal get total token user locked
# Inputs
  - clientID wallet id
 */
FOUNDATION_EXPORT BOOL ZcnGetUserLockedTotal(NSString* _Nullable clientID, int64_t* _Nullable ret0_, NSError* _Nullable* _Nullable error);

/**
 * ReadPoolLock locks given number of tokes for given duration in read pool.
## Inputs
  - tokens:  sas tokens
  - fee: sas tokens
 */
FOUNDATION_EXPORT NSString* _Nonnull ZcnReadPoolLock(NSString* _Nullable tokens, NSString* _Nullable fee, NSError* _Nullable* _Nullable error);

/**
 * ReadPoolUnLock unlocks all the tokens in the readpool associated with the current wallet.
## Inputs
  - fee: sas tokens
 */
FOUNDATION_EXPORT NSString* _Nonnull ZcnReadPoolUnLock(NSString* _Nullable fee, NSError* _Nullable* _Nullable error);

/**
 * WritePoolLock locks given number of tokes for given duration in read pool.
## Inputs
  - allocID: allocation id
  - tokens:  sas tokens
  - fee: sas tokens
 */
FOUNDATION_EXPORT NSString* _Nonnull ZcnWritePoolLock(NSString* _Nullable allocID, NSString* _Nullable tokens, NSString* _Nullable fee, NSError* _Nullable* _Nullable error);

#endif
