// Objective-C API for talking to github.com/0chain/gosdk/core/common Go package.
//   gobind -lang=objc github.com/0chain/gosdk/core/common
//
// File is generated by gobind. Do not edit.

#ifndef __Common_H__
#define __Common_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


// skipped const MZCN with unsupported type: github.com/0chain/gosdk/core/common.BalanceUnit

// skipped const SAS with unsupported type: github.com/0chain/gosdk/core/common.BalanceUnit

// skipped const UZCN with unsupported type: github.com/0chain/gosdk/core/common.BalanceUnit

// skipped const ZCN with unsupported type: github.com/0chain/gosdk/core/common.BalanceUnit


@interface Common : NSObject
+ (NSError* _Nullable) errInvalidTime;
+ (void) setErrInvalidTime:(NSError* _Nullable)v;

@end

// skipped function AutoFormatBalance with unsupported parameter or return types


FOUNDATION_EXPORT NSString* _Nonnull CommonAutoFormatStatic(int64_t amount);

// skipped function FormatBalance with unsupported parameter or return types


FOUNDATION_EXPORT NSString* _Nonnull CommonFormatStatic(int64_t amount, NSString* _Nullable unit);

// skipped function GetPathFields with unsupported parameter or return types


FOUNDATION_EXPORT long CommonMustAddInt(long a, long b);

// skipped function Now with unsupported parameter or return types


// skipped function ParseBalance with unsupported parameter or return types


FOUNDATION_EXPORT BOOL CommonParseBalanceStatic(NSString* _Nullable str, int64_t* _Nullable ret0_, NSError* _Nullable* _Nullable error);

// skipped function ParseTime with unsupported parameter or return types


// skipped function ToBalance with unsupported parameter or return types


FOUNDATION_EXPORT BOOL CommonTryAddInt(long a, long b, long* _Nullable ret0_, NSError* _Nullable* _Nullable error);

#endif
